routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\AgentController;
use App\Http\Controllers\VehicleController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if(Auth::check())
        return redirect()->route('dashboard');
    else
        return redirect()->route('login');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::middleware(['auth:sanctum'])->resource('vehicle', VehicleController::class);
Route::middleware(['auth:sanctum'])->resource('transaction', TransactionController::class)->except(['show']);
Route::middleware(['auth:sanctum'])->resource('users', UserController::class);
Route::middleware(['auth:sanctum'])->resource('roles', RoleController::class);
Route::middleware(['auth:sanctum'])->resource('agents', AgentController::class);
Route::middleware(['auth:sanctum'])->get('admin', [AdminController::class, 'index'])->name('admin.index');
Route::middleware(['auth:sanctum'])->get('admin/expense', [AdminController::class, 'expense'])->name('admin.expense.list');
Route::middleware(['auth:sanctum'])->get('admin/expense/create', [AdminController::class, 'createExpense'])->name('admin.expense.create');
Route::middleware(['auth:sanctum'])->post('admin/expense/store', [AdminController::class, 'storeExpense'])->name('admin.expense.store');
Route::middleware(['auth:sanctum'])->get('admin/transaction/list', [TransactionController::class, 'index'])->name('admin.transaction.list');
Route::middleware(['auth:sanctum'])->get('transaction/end', [TransactionController::class, 'end'])->name('transaction.end');
Route::middleware(['auth:sanctum'])->get('transaction/income', [TransactionController::class, 'income'])->name('transaction.income');


Route::middleware(['auth:sanctum'])->get('reports', [ReportController::class, 'index'])->name('reports.index');
Route::middleware(['auth:sanctum'])->post('reports/transactions', [ReportController::class, 'transactions'])->name('reports.transactions');
Route::middleware(['auth:sanctum'])->post('reports/balance', [ReportController::class, 'balance'])->name('reports.balance');
Route::middleware(['auth:sanctum'])->post('reports/vehicles/active', [ReportController::class, 'activeVehicles'])->name('reports.vehicles.active');
Route::middleware(['auth:sanctum'])->post('reports/vehicles/inactive', [ReportController::class, 'inactiveVehicles'])->name('reports.vehicles.inactive');
Route::middleware(['auth:sanctum'])->post('reports/vehicles', [ReportController::class, 'vehicles'])->name('reports.vehicles');
Route::middleware(['auth:sanctum'])->post('reports/commissions', [ReportController::class, 'commissions'])->name('reports.commissions');
Route::middleware(['auth:sanctum'])->post('reports/topUnsold', [ReportController::class, 'topUnsold'])->name('reports.topUnsold');
Route::middleware(['auth:sanctum'])->post('reports/vehicles/inventory', [ReportController::class, 'inventory'])->name('reports.vehicles.inventory');
Route::middleware(['auth:sanctum'])->post('reports/expenses', [ReportController::class, 'expenses'])->name('reports.expenses');
Route::middleware(['auth:sanctum'])->post('reports/pawn', [ReportController::class, 'pawn'])->name('reports.pawn');

Route::post('brand/type', [FormController::class, 'brandType'])->name('brand.type');
Route::post('reference/brand/type', [FormController::class, 'referenceBrand'])->name('reference.brand');

//Please only in production
/*
Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path("app/public/$filename");

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
})->where('filename', '.*');
*/

app/Models/TransactionType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TransactionType extends Model
{
    use HasFactory;

    protected $fillable = ['description', 'entry', 'end', 'expense', 'income', 'status'];

    public function transactions(){
        return $this->hasMany(Transaction::class);
    }

    public function scopeEntry($query){
        return $query->where('entry', true);
    }

    public function scopeEnd($query){
        return $query->where('end', true);
    }

    public function scopeExpense($query){
        return $query->where('expense', true);
    }

    public function scopeIncome($query){
        return $query->where('income', true);
    }

    public function scopeWithdrawal($query){
        return $query->where('withdrawal', true);
    }

    public function scopePawn($query){
        return $query->where('entry', true)
            ->where('id', 2);
    }
}

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TransactionRequest;
use App\Models\Transaction;
use App\Models\TransactionType;
use App\Models\Agent;
use App\Models\Vehicle;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class TransactionController extends Controller
{
    public function __construct(){
        $this->middleware('role:Admin|Registro');
    }

    public function index(){
        $transactions = Transaction::orderBy('created_at', 'desc')->paginate(10);
        return view('transactions.index', [
            'transactions' => $transactions
        ]);
    }

    public function edit($id){
        $transaction = Transaction::find($id);
        return view('transactions.edit', [
            'transaction' => $transaction
        ]);
    }

    public function end(Request $request){
        $transaction_types = TransactionType::where('end', true)->where('is_active', true)->get();
        $agents = Agent::where('is_active', true)->get();
        return view('transactions.create', [
            'transaction_types' => $transaction_types,
            'agents' => $agents,
            'vehicle' => $request->vehicle,
            'is_active' => 'false',
            'expense' => false,
            'income' => false
        ]);
    }

    public function create(Request $request){
        $transaction_types = TransactionType::where('expense', true)->where('is_active', true)->get();
        $agents = Agent::where('is_active', true)->get();
        return view('transactions.create', [
            'transaction_types' => $transaction_types,
            'agents' => $agents,
            'vehicle' => $request->vehicle,
            'is_active' => 'true',
            'expense' => true,
            'income' => false
        ]);
    }

    public function income(Request $request){
        $transaction_types = TransactionType::where('is_active', true)->where(function ($query){
            $query->where('income', true)->orWhere('withdrawal', true);
        })->get();
        $agents = Agent::where('is_active', true)->get();
        return view('transactions.create', [
            'transaction_types' => $transaction_types,
            'agents' => $agents,
            'vehicle' => $request->vehicle,
            'is_active' => 'true',
            'expense' => false,
            'income' => true
        ]);
    }

    public function store(TransactionRequest $request){
        $message = __('messages.transaction.created.fail');
        $error = true;
        $is_active = ($request->is_active == "true") ? true : false;
        DB::transaction(function () use($request, &$message, &$error, $is_active){
            $support = $request->file('support');
            if(!is_null($request->is_active)){
                Vehicle::where('id', $request->vehicle)->update([
                    'is_active' => $is_active
                ]);
            }
            Transaction::create([
                'vehicle_id' => $request->vehicle,
                'transaction_type' => $request->transaction_type,
                'value' => $request->value,
                'date' => $request->date,
                'support' => is_null($support) ? null : $support->store('transactions', 'public'),
                'agent_id' => $request->agent,
                'commission' => is_null($request->commission) ? 0 : $request->commission,
                'user_id' => Auth::user()->id
            ]);

            $message = trans('messages.transaction.created.done');
            $error = false;
        });

        if($request->vehicle){
            return redirect()->route('vehicle.show', Vehicle::find($request->vehicle))->with([
                'error' => $error,
                'message' => $message
            ]);
        }else{
            return redirect()->route('transaction.income')->with([
                'error' => $error,
                'message' => $message
            ]);
        }
    }

    public function update(Request $request, $id){
        $message = __('messages.transaction.updated.fail');
        $error = true;

        $this->validate($request, [
            'value' => 'required|numeric',
        ]);

        $transaction = Transaction::find($id);
        $transaction->value = $request->value;
        if($request->commission){
            $transaction->commission = $request->commission;
        }
        $transaction->save();

        $error = false;
        $message = __('messages.transaction.updated.done');

        return redirect()->action([TransactionController::class, 'index'])
                        ->with([
                            'error' => $error,
                            'message' => $message
                        ]);
    }

    public function destroy(Transaction $transaction){
        $message = __('messages.transaction.deleted.fail');
        $error = true;

        if($transaction->hasSupport()){
            Storage::delete($transaction->urlSupport);
        }
        if($transaction->isEnd()){
            $vehicle = $transaction->vehicle;
            $vehicle->is_active = true;
            $vehicle->save();
            $transaction->delete();
        }
        if($transaction->isEntry()){
            $vehicle = $transaction->vehicle;
            $transactions = $vehicle->transactions;
            foreach($transactions as $t){
                $t->delete();
            }
            Storage::delete($vehicle->url);
            $vehicle->delete();
        }
        $transaction->delete();

        $error = false;
        $message = __('messages.transaction.deleted.done');

        return redirect()->action([TransactionController::class, 'index'])
                        ->with([
                            'error' => $error,
                            'message' => $message
                        ]);
    }
}

app/Http/Livewire/TransactionsTable.php
<?php

namespace App\Http\Livewire;

use App\Exports\TransactionsExport;
use App\Models\Transaction;
use Livewire\Component;
use Livewire\WithPagination;
use Maatwebsite\Excel\Facades\Excel;

class TransactionsTable extends Component
{
    use WithPagination;

    public $initialDate;
    public $endDate;

    public function render()
    {
        $transactions = Transaction::between($this->initialDate, $this->endDate)->paginate(10);
        return view('livewire.transactions-table', [
            'transactions' => $transactions
        ]);
    }

    public function exportCSV(){
        $transactions = Transaction::between($this->initialDate, $this->endDate)
            ->leftJoin('transaction_types', 'transaction_types.id', '=', 'transactions.transaction_type')
            ->leftJoin('vehicles', 'vehicles.id', '=', 'transactions.vehicle_id')
            ->leftJoin('vehicle_brands', 'vehicle_brands.id', '=', 'vehicles.brand')
            ->leftJoin('vehicle_references', 'vehicle_references.id', '=', 'vehicles.reference')
            ->leftJoin('agents', 'agents.id', '=', 'transactions.agent_id')
            ->orderBy('transactions.date')
            ->orderBy('transactions.created_at');
        return response()->streamDownload(function() use($transactions){
            echo $transactions->toCsv(config('exports.transactions.csv'));
        }, trans_choice('tags.transaction', 2).time().'.csv');
    }

    public function exportXLS(){
        return Excel::download(
            new TransactionsExport($this->initialDate, $this->endDate, config('exports.transactions.xls')),
                trans_choice('tags.transaction', 2).time().'.xlsx'
            );
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/transactions/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('tags.create') }} {{ trans_choice('tags.transaction', 1) }}
        </h2>
    </x-slot>
    <form action="{{ route('transaction.store') }}" enctype="multipart/form-data" method="post">
        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <x-message-card/>
                <x-error-list/>
                <div class="md:grid md:grid-cols-3 md:gap-6">
                    <div class="md:col-span-1">
                        <input type="hidden" name="expense" value="{{ $expense ?? null }}"/>
                        <input type="hidden" name="income" value="{{ $income ?? null }}"/>
                        @if(!$income)
                            @if(!isset($vehicle) && empty($vehicle))
                                @livewire('select-list-vehicle')
                            @else
                                <input type="hidden" name="vehicle" value="{{ $vehicle }}"/>
                                <input type="hidden" name="is_active" value="{{ $is_active }}"/>
                                @livewire('vehicle-info', ['vehicle_id' => $vehicle])
                            @endif
                        @endif
                    </div>
                    <div class="md:col-span-2">
                        @livewire('transaction-create-form', [
                            'transaction_types' => $transaction_types,
                            'agents' => $agents,
                            'expense' => $expense ?? null,
                            'income' => $income ?? null
                            ], key(time()))
                    </div>
                </div>
            </div>
        </div>
    </form>
</x-app-layout>

resources/views/transactions/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-row w-full items-center">
            <h2 class="flex-grow font-semibold text-xl text-gray-800 leading-tight">
                {{ trans_choice('tags.transaction', 2) }}
            </h2>
            <a href="{{ route('admin.transaction.list') }}"
                class="text-sm text-gray-700 underline">{{ __('tags.return') }}</a>
        </div>
    </x-slot>

    <div class="py-12" x-data="{showDeleteModal:false}" x-bind:class="{ 'model-open': showDeleteModal }">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <x-message-card />
            <x-error-list />
            <div class="py-3 w-full sm:mx-auto">
                <div class="px-4 py-10 bg-white mx-8 md:mx-0 sm:w-full shadow rounded-3xl sm:p-10">
                        <x-message-card />
                        <x-error-list />
                        <div class="flex items-center space-x-5 justify-items-center pb-5 w-full text-center place-items-center">
                            <div
                                class="h-14 w-14 bg-yellow-200 rounded-full flex flex-shrink-0 justify-center items-center text-yellow-500 text-2xl font-mono">
                                i</div>
                            <div class="block pl-2 font-semibold text-xl self-start text-gray-700">
                                <h2 class="leading-relaxed">
                                    {{ __('tags.edit') . ' ' . trans_choice('tags.transaction', 2) }}</h2>
                                <p class="text-sm text-gray-500 font-normal leading-relaxed">
                                    {{ __('Editar una transacción') }}</p>
                            </div>
                        </div>
                        @if($transaction->hasVehicle())
                        @livewire('vehicle-mini-card-with-image', [
                            'vehicle' => $transaction->vehicle
                        ])
                        @endif
                        @livewire('transaction-card', [
                        'transaction' => $transaction
                        ])
                        <form action="{{ route('transaction.update', $transaction->id) }}" method="post">
                            {{ csrf_field() }}
                            @method('patch')
                            <div class="divide-y divide-gray-200">
                                <div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7 items-center">
                                    <div class="flex flex-col w-1/2 items-center">
                                        <label class="leading-loose">{{ __('tags.value') }}</label>
                                        <input type="number" name="value" value="{{ $transaction->value }}"
                                            class="w-1/3 px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 sm:w-1/2 xs-w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600"
                                            placeholder="{{ __('tags.value') }}">
                                    </div>
                                    @if ($transaction->hasAgent())
                                        <div class="flex flex-col w-1/2 items-center">
                                            <label class="leading-loose">{{ __('tags.commission') }}</label>
                                            <input type="number" name="commission"
                                                value="{{ $transaction->commission }}"
                                                class="w-1/3 px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 sm:w-1/2 xs-w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600"
                                                placeholder="{{ __('tags.value') }}">
                                        </div>
                                    @endif
                                </div>
                                <div class="pt-4 flex items-center space-x-4">
                                    <a href="{{ route('transaction.index') }}"
                                        class="flex justify-center items-center w-full text-gray-900 px-4 py-3 rounded-md focus:outline-none">
                                        <svg class="w-6 h-6 mr-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                                            xmlns="http://www.w3.org/2000/svg">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M6 18L18 6M6 6l12 12"></path>
                                        </svg> {{ __('tags.cancel') }}
                                    </a>
                                    <a @click={showDeleteModal=true} href="#"
                                        class="bg-red-500 flex justify-center items-center w-full text-black px-4 py-3 rounded-md focus:outline-none">
                                        <svg class="w-6 h-6 mr-3" fill="none" xmlns="http://www.w3.org/2000/svg"
                                            fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                        </svg>{{ __('tags.delete') }}
                                    </a>
                                    <button type="submit"
                                        class="bg-green-500 flex justify-center items-center w-full text-white px-4 py-3 rounded-md focus:outline-none">{{ __('tags.save') }}</button>

                                </div>
                            </div>
                        </form>
                </div>
            </div>
        </div>
        <div x-show="showDeleteModal" tabindex="0"
            class="z-40 overflow-auto left-0 top-0 bottom-0 right-0 w-full h-full fixed">
            <div @click.away="showDeleteModal = false" class="z-50 relative p-3 mx-auto my-0 max-w-full"
                style="width: 500px;">
                <div class="bg-white rounded shadow-lg border flex flex-col overflow-hidden px-10 py-10">
                    <div class="text-center py-6 text-2xl text-gray-700">{{ __('messages.transaction.deleted.question') }}</div>
                    <div class="text-center font-light text-gray-700 mb-8">
                        @if($transaction->hasVehicle())
                        @livewire('vehicle-mini-card-with-image', [
                            'vehicle' => $transaction->vehicle
                        ])
                        @endif
                        @livewire('transaction-card', [
                        'transaction' => $transaction
                        ])
                        {{ __('messages.transaction.deleted.warning') }}
                    </div>
                    <div class="flex justify-center">
                        <button @click={showDeleteModal=false}
                            class="bg-gray-300 text-gray-900 rounded hover:bg-gray-200 px-6 py-2 focus:outline-none mx-1">{{ __('tags.cancel') }}</button>
                        <form action="{{ route('transaction.destroy', $transaction->id) }}" method="post">
                            {{ csrf_field() }}
                            @method('delete')
                            <button type="submit"
                                class="bg-red-500 flex justify-center items-center w-full text-black px-4 py-3 rounded-md focus:outline-none">
                                <svg class="w-6 h-6 mr-3" fill="none" xmlns="http://www.w3.org/2000/svg" fill="none"
                                    viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                </svg>{{ __('tags.delete') }}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
</x-app-layout>

resources/views/transactions/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ trans_choice('tags.transaction', 2) }}
        </h2>
    </x-slot>

    <div class="py-12">
        @livewire('transaction-large-list', [
            'transactions' => $transactions
        ])
    </div>
</x-app-layout>