routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\AgentController;
use App\Http\Controllers\VehicleController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if(Auth::check())
        return redirect()->route('dashboard');
    else
        return redirect()->route('login');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::middleware(['auth:sanctum'])->resource('vehicle', VehicleController::class);
Route::middleware(['auth:sanctum'])->resource('transaction', TransactionController::class)->except(['show']);
Route::middleware(['auth:sanctum'])->resource('users', UserController::class);
Route::middleware(['auth:sanctum'])->resource('roles', RoleController::class);
Route::middleware(['auth:sanctum'])->resource('agents', AgentController::class);
Route::middleware(['auth:sanctum'])->get('admin', [AdminController::class, 'index'])->name('admin.index');
Route::middleware(['auth:sanctum'])->get('admin/expense', [AdminController::class, 'expense'])->name('admin.expense.list');
Route::middleware(['auth:sanctum'])->get('admin/expense/create', [AdminController::class, 'createExpense'])->name('admin.expense.create');
Route::middleware(['auth:sanctum'])->post('admin/expense/store', [AdminController::class, 'storeExpense'])->name('admin.expense.store');
Route::middleware(['auth:sanctum'])->get('admin/transaction/list', [TransactionController::class, 'index'])->name('admin.transaction.list');
Route::middleware(['auth:sanctum'])->get('transaction/end', [TransactionController::class, 'end'])->name('transaction.end');
Route::middleware(['auth:sanctum'])->get('transaction/income', [TransactionController::class, 'income'])->name('transaction.income');


Route::middleware(['auth:sanctum'])->get('reports', [ReportController::class, 'index'])->name('reports.index');
Route::middleware(['auth:sanctum'])->post('reports/transactions', [ReportController::class, 'transactions'])->name('reports.transactions');
Route::middleware(['auth:sanctum'])->post('reports/balance', [ReportController::class, 'balance'])->name('reports.balance');
Route::middleware(['auth:sanctum'])->post('reports/vehicles/active', [ReportController::class, 'activeVehicles'])->name('reports.vehicles.active');
Route::middleware(['auth:sanctum'])->post('reports/vehicles/inactive', [ReportController::class, 'inactiveVehicles'])->name('reports.vehicles.inactive');
Route::middleware(['auth:sanctum'])->post('reports/vehicles', [ReportController::class, 'vehicles'])->name('reports.vehicles');
Route::middleware(['auth:sanctum'])->post('reports/commissions', [ReportController::class, 'commissions'])->name('reports.commissions');
Route::middleware(['auth:sanctum'])->post('reports/topUnsold', [ReportController::class, 'topUnsold'])->name('reports.topUnsold');
Route::middleware(['auth:sanctum'])->post('reports/vehicles/inventory', [ReportController::class, 'inventory'])->name('reports.vehicles.inventory');
Route::middleware(['auth:sanctum'])->post('reports/expenses', [ReportController::class, 'expenses'])->name('reports.expenses');
Route::middleware(['auth:sanctum'])->post('reports/pawn', [ReportController::class, 'pawn'])->name('reports.pawn');

Route::post('brand/type', [FormController::class, 'brandType'])->name('brand.type');
Route::post('reference/brand/type', [FormController::class, 'referenceBrand'])->name('reference.brand');

//Please only in production
/*
Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path("app/public/$filename");

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
})->where('filename', '.*');
*/

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/create_expense.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-row w-full items-center">
        <h2 class="flex-grow font-semibold text-xl text-gray-800 leading-tight">
            {{ __('tags.agent') }}
        </h2>
        <a href="{{ route('admin.expense.list') }}" class="text-sm text-gray-700 underline">{{ __('tags.return') }}</a>
        </div>
    </x-slot>

    <div class="py-12">

        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <x-message-card />
            <div class="relative py-3 sm:max-w-xl sm:mx-auto">
                <div class="relative px-4 py-10 bg-white mx-8 md:mx-0 shadow rounded-3xl sm:p-10">
                    <div class="max-w-md mx-auto">
                        <x-message-card />
                        <x-error-list />
                        <div class="flex items-center space-x-5">
                            <div
                                class="h-14 w-14 bg-yellow-200 rounded-full flex flex-shrink-0 justify-center items-center text-yellow-500 text-2xl font-mono">
                                i</div>
                            <div class="block pl-2 font-semibold text-xl self-start text-gray-700">
                                <h2 class="leading-relaxed">{{ __('tags.create')." ".trans_choice('tags.expense',2) }}</h2>
                                <p class="text-sm text-gray-500 font-normal leading-relaxed">
                                    {{ __('Crear un nuevo gasto para la aplicación') }}</p>
                            </div>
                        </div>
                        <form action="{{ route('admin.expense.store') }}" method="post">
                            {{ csrf_field() }}
                            <div class="divide-y divide-gray-200">
                                <div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">
                                    <div class="flex flex-col">
                                        <label class="leading-loose">{{ __('tags.name') }}</label>
                                        <input type="text" name="name"
                                            class="px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600"
                                            placeholder="{{ __('tags.name') }}">
                                    </div>
                                </div>
                                <div class="pt-4 flex items-center space-x-4">
                                    <a
                                        class="flex justify-center items-center w-full text-gray-900 px-4 py-3 rounded-md focus:outline-none">
                                        <svg class="w-6 h-6 mr-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                                            xmlns="http://www.w3.org/2000/svg">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M6 18L18 6M6 6l12 12"></path>
                                        </svg> {{ __('tags.cancel') }}
                                    </a>
                                    <button type="submit"
                                        class="bg-blue-500 flex justify-center items-center w-full text-white px-4 py-3 rounded-md focus:outline-none">{{ __('tags.create') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/expense.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-row w-full items-center">
        <h2 class="flex-grow font-semibold text-xl text-gray-800 leading-tight">
            {{ __('tags.agent') }}
        </h2>
        <a href="{{ route('admin.index') }}" class="text-sm text-gray-700 underline">{{ __('tags.return') }}</a>
        </div>
    </x-slot>
    <div class="py-12">

        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <x-message-card/>
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="flex justify-end pb-5">
                    <div class="flex justify-end pb-5">
                        <a href="{{ route('admin.expense.create') }}" class="bg-green-600 hover:bg-green-700 rounded-md text-white py-2 px-4 font-bold">
                            <x-heroicon-o-plus-circle class="w-10 h-10"/>
                            <p>{{ __('tags.create') }}</p>
                        </a>
                    </div>
                </div>
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th scope="col"
                                    class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    {{ __('tags.name') }}
                                </th>
                            </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-200">
                            @foreach($expenses as $expense)
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500">
                                    {{ $expense->description }}
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('tags.administration') }}
        </h2>
    </x-slot>

    <style>
        .dark{color:rgba(55, 65, 81,1);}
        body{background:white !important;}
      </style>

    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 mt-6">
        <div class="bg-transparent overflow-auto shadow-xl sm:rounded-lg">
            <div class="holder">

                <div class="card border w-96 hover:shadow-none relative flex flex-col mx-auto shadow-lg m-5">
                  <div class="profile w-full flex m-3 ml-4 text-black dark">
                    <div
                        class="h-24 w-24 bg-green-200 rounded-full flex flex-shrink-0 justify-center items-center text-green-600 text-2xl font-mono">
                        U</div>
                    <div class="title mt-11 ml-3 font-bold flex flex-col">
                      <div class="name break-words">{{ trans_choice('tags.user', 2) }}</div>
                    </div>
                  </div>
                  <div class="buttons flex absolute bottom-0 font-bold right-0 text-xs text-gray-500 space-x-0 my-3.5 mr-3">
                    <div class="add border rounded-l-2xl rounded-r-sm border-gray-300 p-1 px-4 cursor-pointer hover:bg-gray-700 hover:text-white">
                        <a href="{{ route('users.index') }}" class="text-black px-4 py-3 rounded-md focus:outline-none">
                            {{ __('tags.access') }}
                        </a>
                    </div>
                  </div>
                </div>
                <!-- card end -->
                <div class="card border w-96 hover:shadow-none relative flex flex-col mx-auto shadow-lg m-5">
                  <div class="profile w-full flex m-3 ml-4 text-black">
                    <div
                        class="h-24 w-24 bg-green-200 rounded-full flex flex-shrink-0 justify-center items-center text-green-600 text-2xl font-mono">
                        R</div>
                    <div class="title mt-11 ml-3 font-bold flex flex-col">
                        <div class="name break-words">{{ trans_choice('tags.role', 2) }}</div>
                    </div>
                  </div>
                  <div class="buttons flex absolute bottom-0 font-bold right-0 text-xs text-gray-500 space-x-0 my-3.5 mr-3">
                    <div class="add border rounded-l-2xl rounded-r-sm border-gray-300 p-1 px-4 cursor-pointer hover:bg-gray-700 hover:text-white">
                        <a href="{{ route('roles.index') }}" class="text-black px-4 py-3 rounded-md focus:outline-none">
                            {{ __('tags.access') }}
                        </a>
                    </div>
                  </div>
                </div>
                <!-- card end -->
                <div class="card border w-96 hover:shadow-none relative flex flex-col mx-auto shadow-lg m-5">
                  <div class="profile w-full flex m-3 ml-4 text-black">
                    <div
                        class="h-24 w-24 bg-green-200 rounded-full flex flex-shrink-0 justify-center items-center text-green-600 text-2xl font-mono">
                        A</div>
                    <div class="title mt-11 ml-3 font-bold flex flex-col">
                        <div class="name break-words">{{ trans_choice('tags.agent', 2) }}</div>
                    </div>
                  </div>
                  <div class="buttons flex absolute bottom-0 font-bold right-0 text-xs text-gray-500 space-x-0 my-3.5 mr-3">
                    <div class="add border rounded-l-2xl rounded-r-sm border-gray-300 p-1 px-4 cursor-pointer hover:bg-gray-700 hover:text-white">
                        <a href="{{ route('agents.index') }}" class="text-black px-4 py-3 rounded-md focus:outline-none">
                            {{ __('tags.access') }}
                        </a>
                    </div>
                  </div>
                </div>
                <!-- card end -->
                <div class="card border w-96 hover:shadow-none relative flex flex-col mx-auto shadow-lg m-5">
                    <div class="profile w-full flex m-3 ml-4 text-black">
                      <div
                          class="h-24 w-24 bg-green-200 rounded-full flex flex-shrink-0 justify-center items-center text-green-600 text-2xl font-mono">
                          G</div>
                      <div class="title mt-11 ml-3 font-bold flex flex-col">
                          <div class="name break-words">{{ trans_choice('tags.expense', 2) }}</div>
                      </div>
                    </div>
                    <div class="buttons flex absolute bottom-0 font-bold right-0 text-xs text-gray-500 space-x-0 my-3.5 mr-3">
                      <div class="add border rounded-l-2xl rounded-r-sm border-gray-300 p-1 px-4 cursor-pointer hover:bg-gray-700 hover:text-white">
                          <a href="{{ route('admin.expense.list') }}" class="text-black px-4 py-3 rounded-md focus:outline-none">
                              {{ __('tags.access') }}
                          </a>
                      </div>
                    </div>
                  </div>
                  <!-- card end -->
                  <div class="card border w-96 hover:shadow-none relative flex flex-col mx-auto shadow-lg m-5">
                    <div class="profile w-full flex m-3 ml-4 text-black">
                      <div
                          class="h-24 w-24 bg-green-200 rounded-full flex flex-shrink-0 justify-center items-center text-green-600 text-2xl font-mono">
                          T</div>
                      <div class="title mt-11 ml-3 font-bold flex flex-col">
                          <div class="name break-words">{{ __('tags.update').' '.trans_choice('tags.transaction', 2) }}</div>
                      </div>
                    </div>
                    <div class="buttons flex absolute bottom-0 font-bold right-0 text-xs text-gray-500 space-x-0 my-3.5 mr-3">
                      <div class="add border rounded-l-2xl rounded-r-sm border-gray-300 p-1 px-4 cursor-pointer hover:bg-gray-700 hover:text-white">
                          <a href="{{ route('admin.transaction.list') }}" class="text-black px-4 py-3 rounded-md focus:outline-none">
                              {{ __('tags.access') }}
                          </a>
                      </div>
                    </div>
                  </div>
                  <!-- card end -->
              </div>
        </div>
    </div>
</x-app-layout>